/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "boost.browser-logs": [],
    "matrix.index": [],
    "matrix.stream": [],
    "matrix.pomodoro.show": [],
    "matrix.pomodoro.start": [],
    "matrix.pomodoro.pause": [],
    "matrix.pomodoro.skip": [],
    "matrix.pomodoro.reset": [],
    "matrix.pomodoro.settings": [],
    "matrix.pomodoro.active-todo": [],
    "matrix.pomodoro.focus": [],
    "matrix.web-push.vapid": [],
    "matrix.web-push.status": [],
    "matrix.web-push.subscribe": [],
    "matrix.web-push.unsubscribe": [],
    "matrix.web-push.presence": [],
    "matrix.update": [
        {
            "name": "id",
            "required": true
        }
    ],
    "matrix.complete": [
        {
            "name": "id",
            "required": true
        }
    ],
    "matrix.backlog.promote": [],
    "todos.projects.index": [],
    "todos.projects.create": [],
    "todos.projects.store": [],
    "todos.projects.edit": [
        {
            "name": "id",
            "required": true
        }
    ],
    "todos.projects.update": [
        {
            "name": "id",
            "required": true
        }
    ],
    "todos.projects.destroy": [
        {
            "name": "id",
            "required": true
        }
    ],
    "todos.index": [],
    "todos.create": [],
    "todos.store": [],
    "todos.edit": [
        {
            "name": "id",
            "required": true
        }
    ],
    "todos.update": [
        {
            "name": "id",
            "required": true
        }
    ],
    "todos.destroy": [
        {
            "name": "id",
            "required": true
        }
    ],
    "home": [],
    "login": [],
    "auth.sso": [],
    "auth.sso.callback": [],
    "auth.google": [],
    "auth.google.callback": [],
    "logout": [],
    "locale.update": [],
    "storage.local": [
        {
            "name": "path",
            "required": true
        }
    ],
    "storage.local.upload": [
        {
            "name": "path",
            "required": true
        }
    ]
}
}
export {};
